apiVersion: apps/v1
kind: Deployment
metadata:
  name: newsfeed-deploy
  labels:
    app: newsfeed-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: newsfeed-app
  template:
    metadata:
      labels:
        app: newsfeed-app
    spec:
      containers:
        - name: newsfeed
          image: nginxdemos/hello       # using demo image for now
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 80
	