apiVersion: v1
kind: Service
metadata:
  name: newsfeed-svc
  labels:
    app: newsfeed-app
spec:
  type: NodePort
  selector:
    app: newsfeed-app
  ports:
    - name: http
      port: 80
      targetPort: 80
      nodePort: 30007
